export const EXAMS = {
  ielts: {
    name: "IELTS",
    track: "Academic",
    accent: "#d94f45",
    duration: 10,
    skills: ["Reading", "Vocabulary", "Writing", "Listening"],
  },
  gre: {
    name: "GRE",
    track: "General Test",
    accent: "#7f5af0",
    duration: 10,
    skills: ["Verbal", "Quantitative", "Writing", "Vocabulary"],
  },
  gmat: {
    name: "GMAT",
    track: "Focus Edition",
    accent: "#168b73",
    duration: 10,
    skills: ["Quantitative", "Verbal", "Data Insights"],
  },
};

export const RESOURCES = [
  {
    id: "ielts-samples",
    exam: "ielts",
    skill: "All skills",
    title: "Official IELTS sample test questions",
    provider: "IELTS",
    description: "Academic and General Training sample tasks, answer keys, and model responses.",
    access: "Free official",
    url: "https://ielts.org/take-a-test/preparation-resources/sample-test-questions",
  },
  {
    id: "ielts-academic",
    exam: "ielts",
    skill: "Academic",
    title: "IELTS Academic sample tasks",
    provider: "IELTS",
    description: "Timed-format Listening, Reading, Writing, and Speaking practice from the test owners.",
    access: "Free official",
    url: "https://www.ielts.org/take-a-test/preparation-resources/sample-test-questions/academic-test",
  },
  {
    id: "ielts-british-council",
    exam: "ielts",
    skill: "Practice tests",
    title: "Free IELTS practice tests",
    provider: "British Council",
    description: "Skill-by-skill practice for Academic and General Training test formats.",
    access: "Free official",
    url: "https://takeielts.britishcouncil.org/take-ielts/prepare/free-ielts-english-practice-tests",
  },
  {
    id: "ielts-idp",
    exam: "ielts",
    skill: "Practice tests",
    title: "IELTS preparation materials",
    provider: "IDP IELTS",
    description: "Practice activities and preparation guidance across all four skills.",
    access: "Free official",
    url: "https://ielts.idp.com/prepare/all-test-types/all-skills/practice-test",
  },
  {
    id: "gre-prepare",
    exam: "gre",
    skill: "All sections",
    title: "Prepare for the GRE General Test",
    provider: "ETS",
    description: "Official section overviews, strategies, Math Review, and preparation tools.",
    access: "Free official",
    url: "https://www.ets.org/gre/test-takers/general-test/prepare.html",
  },
  {
    id: "gre-powerprep",
    exam: "gre",
    skill: "Mock tests",
    title: "POWERPREP practice tests",
    provider: "ETS",
    description: "Two free browser-based practice tests plus the official preview tool.",
    access: "Free official",
    url: "https://www.ets.org/gre/test-takers/general-test/prepare/powerprep.html",
  },
  {
    id: "gre-accessible",
    exam: "gre",
    skill: "Accessible prep",
    title: "Accessible GRE preparation materials",
    provider: "ETS",
    description: "Alternative formats for the practice book, Math Review, conventions, and strategies.",
    access: "Free official",
    url: "https://www.ets.org/gre/test-takers/general-test/prepare/test-prep-accessible-formats.html",
  },
  {
    id: "gmat-prep",
    exam: "gmat",
    skill: "All sections",
    title: "Prepare for the GMAT exam",
    provider: "mba.com",
    description: "Official prep strategy, free Starter Kit, sample questions, and practice exams.",
    access: "Free official",
    url: "https://www.mba.com/exams/gmat-exam/prep-for-the-exam",
  },
  {
    id: "gmat-support",
    exam: "gmat",
    skill: "Study plan",
    title: "GMAT official prep products and resources",
    provider: "GMAC",
    description: "Current guide to the free Starter Kit, practice exams, and official prep platform.",
    access: "Free official",
    url: "https://support.mba.com/hc/en-us/articles/16086220161051-GMAT-Official-Prep-Products-and-Study-Resources",
  },
];

export const QUESTIONS = [
  {
    id: "ielts-reading-1",
    exam: "ielts",
    skill: "Reading",
    difficulty: "Medium",
    passage: "A city library extended its weekend hours for a twelve-week trial. Visitor numbers rose by 18 percent, while weekday attendance remained stable. The library will review staffing costs before deciding whether to make the change permanent.",
    prompt: "Which statement is supported by the passage?",
    choices: [
      "Weekday attendance fell during the trial.",
      "The longer hours have already become permanent.",
      "More people visited during the trial period.",
      "Staffing costs decreased by 18 percent.",
    ],
    answer: 2,
    explanation: "The passage states that visitor numbers rose by 18 percent. It does not say the change is permanent or that staffing costs fell.",
  },
  {
    id: "ielts-reading-2",
    exam: "ielts",
    skill: "Reading",
    difficulty: "Easy",
    passage: "The research team expected the seedlings in blue light to grow tallest. Instead, those under a balanced white light grew an average of four centimetres more over six weeks.",
    prompt: "The experiment's result was different from the team's expectation.",
    choices: ["True", "False", "Not given", "Both true and false"],
    answer: 0,
    explanation: "The team predicted blue light would work best, but balanced white light produced taller seedlings.",
  },
  {
    id: "ielts-vocab-1",
    exam: "ielts",
    skill: "Vocabulary",
    difficulty: "Medium",
    prompt: "Choose the best word: The report provides a ___ overview of the causes, covering economic, social, and environmental factors.",
    choices: ["comprehensive", "scarce", "temporary", "reluctant"],
    answer: 0,
    explanation: "Comprehensive means complete and covering all or nearly all relevant elements.",
  },
  {
    id: "ielts-language-1",
    exam: "ielts",
    skill: "Writing",
    difficulty: "Hard",
    prompt: "Which sentence uses comparison most precisely?",
    choices: [
      "Car use was more higher than rail use.",
      "Car use exceeded rail use by 12 percentage points.",
      "Car use was very over rail use.",
      "Car use was higher from rail use by 12 percent points.",
    ],
    answer: 1,
    explanation: "“Exceeded … by 12 percentage points” states the comparison and unit precisely without a double comparative.",
  },
  {
    id: "ielts-reading-3",
    exam: "ielts",
    skill: "Reading",
    difficulty: "Hard",
    passage: "Remote work reduced commuting time for most survey participants, yet the average time spent working increased. Researchers cautioned that the survey measured self-reported habits and did not establish that remote work caused the increase.",
    prompt: "What limitation do the researchers identify?",
    choices: [
      "The participants had no commuting time.",
      "The results prove a causal relationship.",
      "The data depends on participants' own reports.",
      "Average working time decreased.",
    ],
    answer: 2,
    explanation: "The explicit limitation is that habits were self-reported, and the researchers avoid a causal claim.",
  },
  {
    id: "ielts-vocab-2",
    exam: "ielts",
    skill: "Vocabulary",
    difficulty: "Easy",
    prompt: "Which word is closest in meaning to “decline” in the phrase “a decline in sales”?",
    choices: ["decrease", "debate", "forecast", "benefit"],
    answer: 0,
    explanation: "In this context, decline is a reduction or decrease.",
  },
  {
    id: "gre-verbal-1",
    exam: "gre",
    skill: "Verbal",
    difficulty: "Medium",
    prompt: "Although the critic was known for severe reviews, her assessment of the debut novel was unexpectedly ___.",
    choices: ["acerbic", "magnanimous", "perfunctory", "incoherent"],
    answer: 1,
    explanation: "Although signals a contrast with severe; magnanimous, meaning generous, supplies that contrast.",
  },
  {
    id: "gre-verbal-2",
    exam: "gre",
    skill: "Verbal",
    difficulty: "Hard",
    passage: "The historian does not deny that trade affected the city's growth. She disputes only the conventional claim that trade was the primary cause, pointing instead to earlier changes in land law.",
    prompt: "The historian's main purpose is to",
    choices: [
      "reject any role for trade",
      "replace a dominant explanation with an earlier cause",
      "show that land law followed commercial growth",
      "argue that the city did not grow",
    ],
    answer: 1,
    explanation: "She accepts that trade had an effect but argues that earlier legal changes were more fundamental.",
  },
  {
    id: "gre-quant-1",
    exam: "gre",
    skill: "Quantitative",
    difficulty: "Easy",
    prompt: "A jacket priced at $80 is discounted by 25%. What is the sale price?",
    choices: ["$20", "$55", "$60", "$65"],
    answer: 2,
    explanation: "The discount is 0.25 × 80 = 20, so the sale price is 80 − 20 = 60.",
  },
  {
    id: "gre-quant-2",
    exam: "gre",
    skill: "Quantitative",
    difficulty: "Medium",
    prompt: "If x + y = 12 and x − y = 4, what is the value of x?",
    choices: ["4", "6", "8", "16"],
    answer: 2,
    explanation: "Adding the equations gives 2x = 16, so x = 8.",
  },
  {
    id: "gre-quant-3",
    exam: "gre",
    skill: "Quantitative",
    difficulty: "Hard",
    prompt: "A data set has mean 18. If a value of 10 is replaced by 25, the mean becomes 21. How many values are in the set?",
    choices: ["3", "5", "7", "15"],
    answer: 1,
    explanation: "The total increases by 15 while the mean increases by 3. Therefore the set contains 15 ÷ 3 = 5 values.",
  },
  {
    id: "gre-verbal-3",
    exam: "gre",
    skill: "Vocabulary",
    difficulty: "Medium",
    prompt: "Choose the word closest in meaning to “laconic.”",
    choices: ["brief", "ornate", "uncertain", "hostile"],
    answer: 0,
    explanation: "Laconic describes speech or writing that uses very few words.",
  },
  {
    id: "gmat-quant-1",
    exam: "gmat",
    skill: "Quantitative",
    difficulty: "Medium",
    prompt: "A machine produces 120 components in 8 minutes at a constant rate. How many components will it produce in 14 minutes?",
    choices: ["180", "200", "210", "224"],
    answer: 2,
    explanation: "The rate is 15 components per minute, so 15 × 14 = 210.",
  },
  {
    id: "gmat-verbal-1",
    exam: "gmat",
    skill: "Verbal",
    difficulty: "Medium",
    prompt: "A retailer concludes that extending store hours increased revenue because revenue rose during the same month. Which fact most weakens the conclusion?",
    choices: [
      "The store hired two additional cashiers.",
      "A citywide festival brought unusually high foot traffic that month.",
      "Some customers prefer shopping in the morning.",
      "The retailer also sells products online.",
    ],
    answer: 1,
    explanation: "The festival is a plausible alternative cause of the revenue increase, weakening the claimed causal link.",
  },
  {
    id: "gmat-data-1",
    exam: "gmat",
    skill: "Data Insights",
    difficulty: "Easy",
    passage: "Quarterly subscriptions: Q1 240; Q2 300; Q3 270; Q4 360.",
    prompt: "Between which consecutive quarters was the percentage increase greatest?",
    choices: ["Q1 to Q2", "Q2 to Q3", "Q3 to Q4", "The increases were equal"],
    answer: 2,
    explanation: "Q1 to Q2 rises 25%. Q3 to Q4 rises 90 ÷ 270, or about 33.3%, which is greater.",
  },
  {
    id: "gmat-quant-2",
    exam: "gmat",
    skill: "Quantitative",
    difficulty: "Hard",
    prompt: "A positive integer n leaves a remainder of 2 when divided by 5. Which expression must be divisible by 5?",
    choices: ["n + 2", "n + 3", "2n + 2", "3n + 3"],
    answer: 1,
    explanation: "n = 5k + 2, so n + 3 = 5k + 5, which is divisible by 5.",
  },
  {
    id: "gmat-verbal-2",
    exam: "gmat",
    skill: "Verbal",
    difficulty: "Hard",
    passage: "A company survey found that teams using a new planning tool completed projects sooner. The survey, however, included only teams that had voluntarily adopted the tool.",
    prompt: "Which concern most directly affects the reliability of the conclusion?",
    choices: [
      "Projects can differ in duration.",
      "The tool has several interface themes.",
      "Self-selection may distinguish adopters from other teams.",
      "Some projects require written plans.",
    ],
    answer: 2,
    explanation: "Voluntary adoption creates selection bias: adopters may differ in ways that also improve completion time.",
  },
  {
    id: "gmat-data-2",
    exam: "gmat",
    skill: "Data Insights",
    difficulty: "Medium",
    passage: "A campaign generated 400 visits from email with a 6% conversion rate and 600 visits from search with a 4% conversion rate.",
    prompt: "How many conversions did the two channels generate in total?",
    choices: ["24", "36", "48", "60"],
    answer: 2,
    explanation: "Email generated 400 × 0.06 = 24 conversions and search generated 600 × 0.04 = 24, for 48 total.",
  },
];

export const VOCABULARY = [
  { id: "ielts-v-1", exam: "ielts", word: "coherent", definition: "Logical, consistent, and easy to understand", example: "The essay presents a coherent argument from evidence to conclusion." },
  { id: "ielts-v-2", exam: "ielts", word: "fluctuate", definition: "To rise and fall irregularly", example: "Energy prices fluctuated throughout the period." },
  { id: "ielts-v-3", exam: "ielts", word: "prevalent", definition: "Common or widespread in a particular area or time", example: "Remote work is increasingly prevalent in service industries." },
  { id: "ielts-v-4", exam: "ielts", word: "mitigate", definition: "To make something harmful less severe", example: "Tree cover can mitigate the urban heat-island effect." },
  { id: "ielts-v-5", exam: "ielts", word: "subsequent", definition: "Coming after something in time", example: "Subsequent studies reached a similar conclusion." },
  { id: "ielts-v-6", exam: "ielts", word: "allocate", definition: "To distribute resources for a purpose", example: "The council allocated more funding to public transport." },
  { id: "gre-v-1", exam: "gre", word: "equivocal", definition: "Ambiguous or open to more than one interpretation", example: "The witness gave an equivocal response." },
  { id: "gre-v-2", exam: "gre", word: "laconic", definition: "Using very few words", example: "Her laconic reply ended the discussion." },
  { id: "gre-v-3", exam: "gre", word: "prodigal", definition: "Wastefully extravagant", example: "The prodigal committee exhausted its budget early." },
  { id: "gre-v-4", exam: "gre", word: "sagacious", definition: "Having good judgement and foresight", example: "The sagacious adviser anticipated the policy's side effects." },
  { id: "gre-v-5", exam: "gre", word: "obdurate", definition: "Stubbornly refusing to change", example: "The board remained obdurate despite new evidence." },
  { id: "gre-v-6", exam: "gre", word: "ephemeral", definition: "Lasting for a very short time", example: "The trend proved ephemeral." },
  { id: "gmat-v-1", exam: "gmat", word: "assumption", definition: "An unstated idea an argument depends on", example: "The conclusion relies on an assumption about customer demand." },
  { id: "gmat-v-2", exam: "gmat", word: "causation", definition: "A relationship in which one event produces another", example: "Correlation alone does not establish causation." },
  { id: "gmat-v-3", exam: "gmat", word: "discrepancy", definition: "A difference between things expected to agree", example: "The analyst investigated the discrepancy in the two reports." },
  { id: "gmat-v-4", exam: "gmat", word: "inference", definition: "A conclusion reached from evidence and reasoning", example: "The inference follows from both data statements." },
  { id: "gmat-v-5", exam: "gmat", word: "constraint", definition: "A limitation or restriction", example: "Budget was the main constraint on expansion." },
  { id: "gmat-v-6", exam: "gmat", word: "viable", definition: "Capable of working successfully", example: "The team tested whether the proposal was financially viable." },
];

export const WRITING_PROMPTS = {
  ielts: [
    "Some people believe cities should invest more in public transport than in roads. Discuss both views and give your opinion.",
    "Online learning is replacing some classroom teaching. Do the advantages outweigh the disadvantages?",
  ],
  gre: [
    "A society should value the ability to question accepted ideas more than the ability to preserve them. Write a response in which you discuss your view.",
    "The best way to understand a culture is to study how it educates its young people. Write a response in which you discuss the claim.",
  ],
  gmat: [
    "Evaluate the reasoning in a proposal that attributes rising customer retention solely to a new loyalty program.",
    "Assess an argument that recommends entering a market because a single competitor reported strong first-year sales.",
  ],
};
